[tool.poetry]
name = "conda-to-poetry"
version = "0.1.0"
description = ""
authors = ["John Saigle <example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
toml = "^0.10.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
